### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by 5opr4ni** [olzzon/casparcg-state-scanner#11]
Hi

I am eager to test this out, working with 2.2, but no luck. 
Doing the test with 2.2 Stable.

this:
```
query{
  serverVersion
}
```

gives:
```
{
  "data": {
    "serverVersion": null
  }
}
```
Am i doing something wrong?

I can't see that the service connects to Caspar.
You are aware that you need to make a TCP (5250) connection to Caspar, before it starts to issue OSC to you! 
Else you have to make it explicit in the config.
Something like this example:
```XML
<osc>
  <disable-send-to-amcp-clients>false</disable-send-to-amcp-clients>
  <predefined-clients>
    <predefined-client>
      <address>10.0.1.3</address>
      <port>6256</port>
    </predefined-client>
  </predefined-clients>
</osc>
```

/Olle
Founder of CasparCG

**Comment by olzzon** [comment]
Yes, I discovered that too.
A new 0.7.2 has fixed this. (and also a version check problem)

https://github.com/olzzon/casparcg-state-scanner/releases

**Comment by olzzon** [comment]
Sorry 0.7.3 will fix it.
Testing right now.....

**Comment by olzzon** [comment]
There we´re 4 issues:
Fixed:
1 - the server version was used before AMCP VERSION had returned it´s promise.
2 - OSC server was initiated before AMCP was called.
3 - a variable "version" was assigned instead of "serverVersion"
Fixed but will be related in next version (as i´m doing code cleanup)
4 - GraphQL query serverVersion was not implemented.
You can try the query if you build the latest develop-branch

**Comment by olzzon** [comment]
I´ll close this one as solved :)
